services:
  api:
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    ports:
      - 3000:3000
    environment:
      AUTH_REALM_URL: http://localhost:8080/realms/dev
  web:
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
    ports:
      - 5173:8080
    environment:
      API_URL: http://localhost:3000
